import streamlit as st
from google import genai
from PIL import Image
import os
from dotenv import load_dotenv

load_dotenv()

# Page config
st.set_page_config(page_title="AgriN - AI Agro Intelligence", layout="wide", page_icon="🌱")

# API Configuration
api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    api_key = st.sidebar.text_input("Enter Gemini API Key:", type="password")

st.title("🌱 AgriN: Regenerative Agro-Intelligence Platform")
st.caption("Empowering Smallholder Farmers with Multimodal AI & Soil Health Analytics")

# Navigation Tabs
tab1, tab2, tab3 = st.tabs(["🍃 Crop Disease Diagnostic", "🌍 Regenerative Soil Advisor", "🌐 BRICS Data Exchange"])

# TAB 1: Multimodal Disease Detection
with tab1:
    st.subheader("Visual Crop Disease Diagnostic")
    lang = st.selectbox("Preferred Advisory Language", ["Tamil", "English", "Hindi", "Telugu"])
    uploaded_file = st.file_uploader("Upload leaf image for inspection", type=["jpg", "jpeg", "png"])
    
    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Crop Leaf", width=300)
        
        if st.button("Analyze Crop Health"):
            if not api_key:
                st.warning("Please enter your Gemini API Key in the sidebar!")
            else:
                with st.spinner("Analyzing leaf with Gemini AI..."):
                    try:
                        client = genai.Client(api_key=api_key)
                        prompt = f"""
                        You are a clinical plant pathologist and regenerative agronomist. Analyze the crop image and return a concise, evidence-based agronomy report strictly in {lang}.
                        Use only these clean Markdown headers, in this order:

                        ## 1. Crop Name and Disease Diagnosis
                        State the crop's common name and scientific name. Identify the most likely disease (or state that no disease is evident), its scientific/causal organism name when known, and confidence level. Do not claim certainty from an image alone.

                        ## 2. Visible Symptoms
                        Describe only symptoms visible in the image, including affected plant parts, lesion or discoloration patterns, and apparent severity. Distinguish observations from inference.

                        ## 3. Non-Chemical Biological Remedies
                        Recommend practical biological measures, including safe Neem oil dilution guidance, Trichoderma use, and Panchagavya where appropriate. Give preparation/application rates, timing, precautions, and mention when local agricultural guidance or a confirmatory diagnosis is needed. Do not recommend synthetic chemical pesticides.

                        ## 4. Regenerative Soil Immunity and Prevention
                        Provide soil-health and regenerative practices to reduce recurrence, such as compost or well-decomposed organic matter, crop rotation, cover crops, mulching, biodiversity, drainage, and balanced nutrition. Tailor advice to the likely disease and clearly label assumptions.
                        """
                        response = client.models.generate_content(
                            model="gemini-3.6-flash",
                            contents=[prompt, image]
                        )
                        st.success("Analysis Complete!")
                        with st.container(border=True):
                            st.markdown(response.text)
                        st.warning(
                            "⚠️ Agro-Advisory Notice: This diagnosis is generated by multimodal AI. "
                            "Verify with local Krishi Vigyan Kendra (KVK) extension officers or agronomists "
                            "before applying treatments."
                        )
                        st.download_button(
                            label="Download Agronomy Report",
                            data=response.text,
                            file_name="agronomy_report.txt",
                            mime="text/plain"
                        )
                    except Exception as e:
                        st.error(f"Error: {e}")

# TAB 2: Soil & Crop Recommendation
with tab2:
    st.subheader("Regenerative Crop & Soil Advisor")
    col1, col2, col3 = st.columns(3)
    with col1:
        nitrogen = st.number_input("Nitrogen (N) level", 0, 200, 50)
    with col2:
        phosphorus = st.number_input("Phosphorus (P) level", 0, 200, 50)
    with col3:
        potassium = st.number_input("Potassium (K) level", 0, 200, 50)
        
    soil_type = st.selectbox("Soil Type", ["Alluvial", "Black Soil", "Red Soil", "Clayey", "Sandy Loam"])
    
    if st.button("Generate Crop Recommendation"):
        if not api_key:
            st.warning("Please enter your Gemini API Key in the sidebar!")
        else:
            with st.spinner("Calculating sustainable crop rotation..."):
                try:
                    client = genai.Client(api_key=api_key)
                    soil_prompt = f"""
                    Provide regenerative crop rotation advice for a farmer with:
                    - Soil Type: {soil_type}
                    - NPK Values: N={nitrogen}, P={phosphorus}, K={potassium}
                    Suggest suitable regenerative crops, cover cropping methods, and natural nitrogen-fixing plants.
                    """
                    res = client.models.generate_content(
                        model="gemini-3.6-flash",
                        contents=soil_prompt
                    )
                    with st.container(border=True):
                        st.markdown(res.text)
                    st.download_button(
                        label="📥 Download Soil Rotation Plan (.txt)",
                        data=res.text,
                        file_name="soil_rotation_plan.txt",
                        mime="text/plain"
                    )
                    st.caption(
                        "💡 Tip: Soil parameters can be periodically retested via local soil health "
                        "card labs to optimize cover crop mix ratios."
                    )
                except Exception as e:
                    st.error(f"Error: {e}")

# TAB 3: BRICS Collaboration Mock Hub
with tab3:
    st.subheader("BRICS Agro-Climatic Intelligence Exchange")
    st.info("Demonstrating cross-border disease surveillance and climate-resilient crop model sharing.")
    corridor_data = {
        "Semi-Arid Grain Belt: India (Deccan Plateau) ↔ Brazil (Cerrado Biome)": {
            "pest": "Spodoptera frugiperda / Fall Armyworm",
            "soc": "-1.15%",
            "drought": "High / Tier-2",
        },
        "Humid Subtropical: India (Gangetic Plain) ↔ China (Yangtze Basin)": {
            "pest": "Nilaparvata lugens / Brown Planthopper",
            "soc": "-0.85%",
            "drought": "Moderate / Tier-2",
        },
        "Drylands & Savanna: India (Thar/Rajasthan) ↔ South Africa (Highveld/Karoo)": {
            "pest": "Schistocerca gregaria / Desert Locust",
            "soc": "-1.40%",
            "drought": "Very High / Tier-1",
        },
    }
    selected_corridor = st.selectbox(
        "Select Agro-Climatic Corridor",
        list(corridor_data.keys())
    )
    selected_data = corridor_data[selected_corridor]

    kpi_col1, kpi_col2, kpi_col3 = st.columns(3)
    with kpi_col1:
        st.metric("Shared Pest / Pathogen Vector", selected_data["pest"])
    with kpi_col2:
        st.metric("Soil Organic Carbon (SOC) Deficit", selected_data["soc"])
    with kpi_col3:
        st.metric("Drought Vulnerability Index", selected_data["drought"])

    inquiry = st.text_input(
        "Cross-Border Regenerative Inquiry",
        value="How can Brazil's direct planting into heavy straw cover (Plantio Direto) be adapted for smallholder sorghum and pulses in the Deccan Plateau?"
    )

    if st.button("Generate Cross-Border Intelligence"):
        if not api_key:
            st.warning("Please enter your Gemini API Key in the sidebar!")
        else:
            with st.spinner("Generating cross-border agro-intelligence..."):
                try:
                    client = genai.Client(api_key=api_key)
                    corridor_prompt = f"""
                    Provide actionable, cross-border agro-intelligence for this agro-climatic corridor:
                    {selected_corridor}

                    Comparative indicators:
                    - Shared pest / pathogen vector: {selected_data["pest"]}
                    - Soil Organic Carbon (SOC) deficit: {selected_data["soc"]}
                    - Drought vulnerability index: {selected_data["drought"]}

                    Farmer inquiry: {inquiry}

                    Compare relevant practices across both regions and recommend practical,
                    regenerative actions suitable for smallholders. Include implementation steps,
                    resource considerations, risks, monitoring indicators, and where local extension
                    validation is needed. Do not recommend unverified or prohibited treatments.
                    """
                    intelligence_response = client.models.generate_content(
                        model="gemini-3.6-flash",
                        contents=corridor_prompt
                    )
                    with st.container(border=True):
                        st.markdown(intelligence_response.text)
                    st.download_button(
                        label="Download Cross-Border Advisory",
                        data=intelligence_response.text,
                        file_name="cross_border_advisory.txt",
                        mime="text/plain"
                    )
                except Exception as e:
                    st.error(f"Error: {e}")